# Generated by Django 3.0.8 on 2020-09-11 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_tab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='release_date',
        ),
        migrations.AddField(
            model_name='shoe',
            name='release_day',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoe',
            name='release_month',
            field=models.IntegerField(default=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='shoe',
            name='release_year',
            field=models.IntegerField(default=19),
            preserve_default=False,
        ),
    ]
