# Generated by Django 3.0.8 on 2020-09-12 22:46

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('shoe_tab', '0003_auto_20200912_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='shoe_name',
            field=models.CharField(default=uuid.uuid1, max_length=128, unique=True),
        ),
    ]
